import Head from 'next/head';
import GlobalLayout from '../layouts/GlobalLayout';

import { TopStatistics, Navbar, Tasks, RapidChainProjects, YourDetails } from '../components';
import { useAccount } from 'wagmi';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
export default function Panel() {

    const account = useAccount();
    
    const router = useRouter()
    


    useEffect(() => {
        if (account.address === undefined) {
          router.push("/");
        }
      }, [account]);

 return (
  <div className="">
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css'/>
   </Head>
   <GlobalLayout>
    <div className="flex flex-col gap-4 w-full">
     <Navbar />
     <YourDetails />
     <TopStatistics />
     <Tasks />
     <RapidChainProjects />
    </div>
    {/*<Navbar />*/}
    {/*<Statistics />*/}
   </GlobalLayout>
  </div>
 );
}
